### PR TITLE
🚀 **Morse Code Decoder in Ruby** 🚀

### PR DESCRIPTION
**Pull request by jicamargo**
# 🚀 **Morse Code Decoder in Ruby** 🚀

✨ This PR adds a Morse Code Decoder program written in Ruby ✨

🆕 **New Features:**

- Create a method to decode a Morse code character, takes a string parameter, and returns the corresponding character in uppercase. 

- Create a method to decode an entire word in Morse code, takes a string parameter, and returns the string representation. Every character in a word will be separated by a single space. 

- Create a method to decode the entire message in Morse code, takes a string parameter, and returns the string representation. Every word will be separated by 3 spaces. 

🔄 **Code Reusability:**

Methods are designed to be reusable, ensuring the code is DRY (Don't Repeat Yourself).

📝 **Note:**

Feel free to provide feedback or suggest any improvements to enhance the program's functionality.

🛠️ **Checklist:**

- [ ] Implemented method to decode a Morse code character.
- [ ] Implemented method to decode an entire word in Morse code.
- [ ] Implemented method to decode the entire message in Morse code.
- [ ] Ensured code is DRY and methods are reused where possible.
- [ ] Added examples and explanations in the code comments.

🚀 Let's merge this PR and make Morse code decoding easier! 🚀

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented: Ensure that provided placeholder texts/ guide instructions are removed and/or replaced with appropriate contents applicable under each section of your ReadMe. 

**Kindly remove/update all aspects similar to the underlined:**
image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jicamargo** [comment]
Thank you @rloterh, Change done! 👍🏼

**Review by rotimiazeez — APPROVED** [review]
Hi TEAM 🎉, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Your code has `#decode_char` method and works as expected 👍🏽
* It has `#decode_word` method and works as expected 👌🏽
* It has `#decode` method and works as expected 👏🏽
* Good teamwork 💯
* Good PR description and title 😉
* No linter error ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jicamargo** [comment]
Thank you @rotimiazeez 👍🏼

**Pull request closed without merging**
